const fs = require('fs').promises;
const path = require('path');

const VEHICLES_FILE = path.join(__dirname, '../src/data/vehicles.json');
const BACKUP_FILE = path.join(__dirname, '../src/data/vehicles.backup.json');

const DEMO_VEHICLES = [
  {
    id: "v1",
    make: "Maruti Suzuki",
    model: "Swift ZXi",
    year: 2024,
    category: "Hatchback",
    fuelType: "Petrol",
    transmission: "Manual",
    price: 820000,
    quantity: 5,
    mileage: "24.8 km/l",
    engine: "1197 cc",
    seatingCapacity: 5,
    color: "Luster Blue",
    location: "Ahmedabad",
    image: "https://images.unsplash.com/photo-1541899481282-d53bffe3c35d?auto=format&fit=crop&w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1541899481282-d53bffe3c35d?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1552519507-da3b142c6e3d?auto=format&fit=crop&w=800&q=80"
    ],
    shortDescription: "India's iconic hatchback offering peppy performance, stylish looks, and class-leading mileage.",
    description: "The Maruti Suzuki Swift is a fun-to-drive, fuel-efficient hatchback designed for urban commutes. Features sport-inspired seating, LED projector headlamps, floating touchscreen, and legendary reliability.",
    features: ["7-inch Touchscreen", "Automatic Climate Control", "Push Button Start", "Dual Airbags", "ABS with EBD"],
    featured: true,
    condition: "New"
  },
  {
    id: "v2",
    make: "Maruti Suzuki",
    model: "Baleno Alpha",
    year: 2024,
    category: "Hatchback",
    fuelType: "Petrol",
    transmission: "Automatic",
    price: 980000,
    quantity: 4,
    mileage: "22.9 km/l",
    engine: "1197 cc",
    seatingCapacity: 5,
    color: "Nexa Blue",
    location: "Mumbai",
    image: "https://images.unsplash.com/photo-1590362891991-f776e747a588?auto=format&fit=crop&w=800&q=80",
    images: ["https://images.unsplash.com/photo-1590362891991-f776e747a588?auto=format&fit=crop&w=800&q=80"],
    shortDescription: "Premium hatchback with Head-Up Display, 360 camera, and spacious comfortable cabin.",
    description: "The Maruti Suzuki Baleno combines sophisticated Nexa design with advanced technology. Features a Head-Up Display, 360-view camera, 9-inch SmartPlay Pro+ infotainment, and refined driving dynamics.",
    features: ["Head-Up Display", "360 Camera", "9-inch Touchscreen", "6 Airbags", "Rear AC Vents"],
    featured: false,
    condition: "New"
  },
  {
    id: "v3",
    make: "Maruti Suzuki",
    model: "Brezza ZXi+",
    year: 2024,
    category: "Compact SUV",
    fuelType: "Petrol",
    transmission: "Automatic",
    price: 1398000,
    quantity: 3,
    mileage: "19.8 km/l",
    engine: "1462 cc",
    seatingCapacity: 5,
    color: "Brave Khaki",
    location: "Delhi",
    image: "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=800&q=80",
    images: ["https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=800&q=80"],
    shortDescription: "Popular urban SUV featuring electric sunroof, wireless charging, and robust road presence.",
    description: "The Maruti Suzuki Brezza offers a confident SUV stance, quiet cabin, and reliable K15C engine. Comes with electric sunroof, ambient lighting, cruise control, and connected car technology.",
    features: ["Electric Sunroof", "Wireless Charging", "HUD", "Ambient Lighting", "ESP with Hill Hold"],
    featured: true,
    condition: "New"
  },
  {
    id: "v4",
    make: "Maruti Suzuki",
    model: "Grand Vitara Strong Hybrid",
    year: 2024,
    category: "SUV",
    fuelType: "Hybrid",
    transmission: "Automatic",
    price: 1980000,
    quantity: 2,
    mileage: "27.9 km/l",
    engine: "1490 cc",
    seatingCapacity: 5,
    color: "Chestnut Brown",
    location: "Bengaluru",
    image: "https://images.unsplash.com/photo-1580273916550-e323be2ae537?auto=format&fit=crop&w=800&q=80",
    images: ["https://images.unsplash.com/photo-1580273916550-e323be2ae537?auto=format&fit=crop&w=800&q=80"],
    shortDescription: "Flagship hybrid SUV delivering unmatched 27.9 km/l fuel efficiency and AWD capabilities.",
    description: "The Grand Vitara Intelligent Electric Hybrid seamlessly switches between electric and petrol drive. Features panoramic sunroof, ventilated front seats, ALLGRIP AWD option, and digital cluster.",
    features: ["Panoramic Sunroof", "Ventilated Seats", "Strong Hybrid EV Mode", "Digital Cluster", "TPMS"],
    featured: true,
    condition: "New"
  },
  {
    id: "v5",
    make: "Hyundai",
    model: "i20 Asta (O)",
    year: 2024,
    category: "Hatchback",
    fuelType: "Petrol",
    transmission: "Automatic",
    price: 1120000,
    quantity: 4,
    mileage: "20.35 km/l",
    engine: "1197 cc",
    seatingCapacity: 5,
    color: "Fiery Red",
    location: "Pune",
    image: "https://images.unsplash.com/photo-1542282088-72c9c27ed0cd?auto=format&fit=crop&w=800&q=80",
    images: ["https://images.unsplash.com/photo-1542282088-72c9c27ed0cd?auto=format&fit=crop&w=800&q=80"],
    shortDescription: "Sleek premium hatchback equipped with Bose premium sound system and electric sunroof.",
    description: "The Hyundai i20 stands out with European parametric styling, 10.25-inch touchscreen infotainment, Bose 7-speaker audio, BlueLink connected tech, and ambient lighting.",
    features: ["Bose Sound System", "10.25 Touchscreen", "Electric Sunroof", "Wireless Phone Charger", "6 Airbags Standard"],
    featured: false,
    condition: "New"
  },
  {
    id: "v6",
    make: "Hyundai",
    model: "Verna SX Turbo",
    year: 2024,
    category: "Sedan",
    fuelType: "Petrol",
    transmission: "Automatic",
    price: 1738000,
    quantity: 3,
    mileage: "20.6 km/l",
    engine: "1482 cc",
    seatingCapacity: 5,
    color: "Abyss Black",
    location: "Ahmedabad",
    image: "https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?auto=format&fit=crop&w=800&q=80",
    images: ["https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?auto=format&fit=crop&w=800&q=80"],
    shortDescription: "Futuristic sedan with 160 PS Turbo GDi engine and Level 2 ADAS safety technology.",
    description: "The next-gen Hyundai Verna delivers thrilling turbocharged performance paired with futuristic horizon light bars, dual integrated screens, heated/ventilated front seats, and 17 ADAS features.",
    features: ["Level 2 ADAS", "160 PS Turbo Engine", "Heated & Ventilated Seats", "Dual Integrated Screens", "Switchable Control Panel"],
    featured: true,
    condition: "New"
  },
  {
    id: "v7",
    make: "Hyundai",
    model: "Creta SX Tech",
    year: 2024,
    category: "SUV",
    fuelType: "Petrol",
    transmission: "Automatic",
    price: 1680000,
    quantity: 5,
    mileage: "17.4 km/l",
    engine: "1497 cc",
    seatingCapacity: 5,
    color: "Polar White",
    location: "Ahmedabad",
    image: "https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?auto=format&fit=crop&w=800&q=80",
    images: ["https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?auto=format&fit=crop&w=800&q=80"],
    shortDescription: "India's favorite SUV offering dominant road presence, panoramic sunroof, and ADAS.",
    description: "The Hyundai Creta is a comfortable and feature-rich compact SUV suitable for city driving and highway journeys. It offers a spacious cabin, modern infotainment, good safety equipment, and refined performance.",
    features: ["Touchscreen Infotainment", "Automatic Climate Control", "Rear Parking Camera", "Cruise Control", "ABS with EBD", "Dual Airbags"],
    featured: true,
    condition: "New"
  },
  {
    id: "v8",
    make: "Hyundai",
    model: "Venue N Line",
    year: 2024,
    category: "Compact SUV",
    fuelType: "Petrol",
    transmission: "Automatic",
    price: 1375000,
    quantity: 4,
    mileage: "18.1 km/l",
    engine: "998 cc",
    seatingCapacity: 5,
    color: "Thunder Blue",
    location: "Hyderabad",
    image: "https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?auto=format&fit=crop&w=800&q=80",
    images: ["https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?auto=format&fit=crop&w=800&q=80"],
    shortDescription: "Sporty compact SUV with sport-tuned suspension, dual exhaust pipes, and N Line styling.",
    description: "The Hyundai Venue N Line brings track-inspired enthusiasm to urban SUV driving. Features dual dashcam with front/rear cameras, N Line leatherette seats, paddle shifters, and 4-disc brakes.",
    features: ["Dual Dashcam", "Sport Exhaust Note", "Paddle Shifters", "All 4 Disc Brakes", "Dark Chrome Grille"],
    featured: false,
    condition: "New"
  },
  {
    id: "v9",
    make: "Tata",
    model: "Nexon Fearless+",
    year: 2024,
    category: "Compact SUV",
    fuelType: "Petrol",
    transmission: "Automatic",
    price: 1470000,
    quantity: 5,
    mileage: "17.01 km/l",
    engine: "1199 cc",
    seatingCapacity: 5,
    color: "Ocean Blue",
    location: "Mumbai",
    image: "https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=800&q=80",
    images: ["https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=800&q=80"],
    shortDescription: "5-Star Global NCAP safety rated SUV with JBL audio, 360 camera, and sequential LED DRLs.",
    description: "The Tata Nexon is a practical compact SUV offering a comfortable cabin, confident road presence, and useful modern features. Its compact dimensions make city driving easy, while the spacious interior and strong safety-focused design make it suitable for small families and regular highway use.",
    features: ["5-Star NCAP Safety Rating", "10.25 Cinematic Touchscreen", "JBL 9-Speaker Audio", "360 HD Camera", "Ventilated Front Seats"],
    featured: true,
    condition: "New"
  },
  {
    id: "v10",
    make: "Tata",
    model: "Punch Creative Flagship",
    year: 2024,
    category: "Compact SUV",
    fuelType: "Petrol",
    transmission: "Manual",
    price: 895000,
    quantity: 6,
    mileage: "20.09 km/l",
    engine: "1199 cc",
    seatingCapacity: 5,
    color: "Tornado Blue",
    location: "Ahmedabad",
    image: "https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=800&q=80",
    images: ["https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=800&q=80"],
    shortDescription: "Sub-compact SUV with 5-star NCAP safety rating and 187mm high ground clearance.",
    description: "The Tata Punch combines micro-SUV versatility with rugged design and class-leading safety. Features 90-degree opening doors, 7-inch Harman infotainment, automatic headlamps, and traction control modes.",
    features: ["5-Star Safety Rating", "187mm Ground Clearance", "90-Degree Door Opening", "Harman Audio", "Rain Sensing Wipers"],
    featured: false,
    condition: "New"
  },
  {
    id: "v11",
    make: "Tata",
    model: "Harrier Fearless Dark",
    year: 2024,
    category: "SUV",
    fuelType: "Diesel",
    transmission: "Automatic",
    price: 2450000,
    quantity: 2,
    mileage: "16.8 km/l",
    engine: "1956 cc",
    seatingCapacity: 5,
    color: "Oberon Black",
    location: "Delhi",
    image: "https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=800&q=80",
    images: ["https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=800&q=80"],
    shortDescription: "Commanding 5-seater SUV built on Land Rover OMEGARC platform architecture.",
    description: "The Tata Harrier Dark Edition commands attention with stealth black styling, Kryotec 170 PS diesel engine, terrain response modes, memory driver seat, gesture powered tailgate, and Level 2 ADAS.",
    features: ["Land Rover D8 Platform", "Kryotec 170 PS Diesel", "12.3-inch Touchscreen", "Gesture Powered Tailgate", "Terrain Response Modes"],
    featured: true,
    condition: "New"
  },
  {
    id: "v12",
    make: "Tata",
    model: "Nexon EV Empowered+",
    year: 2024,
    category: "Electric",
    fuelType: "Electric",
    transmission: "Automatic",
    price: 1949000,
    quantity: 3,
    mileage: "465 km/charge",
    engine: "40.5 kWh Battery",
    seatingCapacity: 5,
    color: "Empowered Oxide",
    location: "Bengaluru",
    image: "https://images.unsplash.com/photo-1560958089-b8a1929cea89?auto=format&fit=crop&w=800&q=80",
    images: ["https://images.unsplash.com/photo-1560958089-b8a1929cea89?auto=format&fit=crop&w=800&q=80"],
    shortDescription: "India's bestselling electric SUV featuring 465 km range and V2L vehicle-to-load charging.",
    description: "The Tata Nexon EV Long Range redefined electric mobility in India. Features Vehicle-to-Load (V2L) power supply, paddle regenerators, arcade.ev app suite, electronic parking brake, and fast DC charging.",
    features: ["465 km Certified Range", "V2L & V2V Charging", "12.3-inch Cinematic Display", "Regen Paddle Shifters", "IP67 Battery Pack"],
    featured: true,
    condition: "New"
  },
  {
    id: "v13",
    make: "Mahindra",
    model: "XUV 3XO AX7L",
    year: 2024,
    category: "Compact SUV",
    fuelType: "Petrol",
    transmission: "Automatic",
    price: 1480000,
    quantity: 4,
    mileage: "20.1 km/l",
    engine: "1197 cc TGDi",
    seatingCapacity: 5,
    color: "Citrine Yellow",
    location: "Pune",
    image: "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=800&q=80",
    images: ["https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=800&q=80"],
    shortDescription: "Feature-packed SUV offering segment-first panoramic skyroof and 130 PS mStallion TGDi engine.",
    description: "The Mahindra XUV 3XO sets benchmark standards with Level 2 ADAS, Harman Kardon 7-speaker audio, widest cabin in segment, dual-zone climate control, and 0-60 km/h acceleration in 4.5 seconds.",
    features: ["Segment Panoramic Skyroof", "130 PS TGDi Engine", "Level 2 ADAS", "Harman Kardon Audio", "Electronic Parking Brake"],
    featured: true,
    condition: "New"
  },
  {
    id: "v14",
    make: "Mahindra",
    model: "Scorpio N Z8L 4XPLOR",
    year: 2024,
    category: "SUV",
    fuelType: "Diesel",
    transmission: "Automatic",
    price: 2450000,
    quantity: 3,
    mileage: "14.5 km/l",
    engine: "2184 cc mHawk",
    seatingCapacity: 7,
    color: "Deep Forest",
    location: "Jaipur",
    image: "https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=800&q=80",
    images: ["https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=800&q=80"],
    shortDescription: "Big daddy of SUVs featuring authentic body-on-frame 4XPLOR terrain management system.",
    description: "The Mahindra Scorpio N delivers unmissable road presence paired with 175 PS mHawk diesel engine power. Features 4XPLOR shift-on-fly terrain response, Sony 3D immersive audio, and 5-star NCAP safety.",
    features: ["4XPLOR Intelligent 4WD", "175 PS mHawk Engine", "Sony 3D 12-Speaker Audio", "5-Star NCAP Rating", "Penta-link Rear Suspension"],
    featured: true,
    condition: "New"
  },
  {
    id: "v15",
    make: "Mahindra",
    model: "XUV700 AX7 Luxury AWD",
    year: 2024,
    category: "SUV",
    fuelType: "Diesel",
    transmission: "Automatic",
    price: 2690000,
    quantity: 2,
    mileage: "16.5 km/l",
    engine: "2184 cc",
    seatingCapacity: 7,
    color: "Midnight Black",
    location: "Ahmedabad",
    image: "https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=800&q=80",
    images: ["https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=800&q=80"],
    shortDescription: "Technologically advanced 7-seater SUV with dual HD superscreen and blind view monitor.",
    description: "The Mahindra XUV700 combines luxurious 7-seater comfort with 185 PS diesel performance and smart door handles. Comes loaded with ADAS Level 2, memory driver seat, wireless Apple CarPlay, and AWD.",
    features: ["Dual 10.25-inch Superscreen", "Level 2 ADAS", "Flush Smart Door Handles", "Sony 3D Sound", "All-Wheel Drive (AWD)"],
    featured: true,
    condition: "New"
  },
  {
    id: "v16",
    make: "Mahindra",
    model: "Thar LX 4WD Hard Top",
    year: 2023,
    category: "SUV",
    fuelType: "Diesel",
    transmission: "Manual",
    price: 1750000,
    quantity: 4,
    mileage: "15.2 km/l",
    engine: "2184 cc",
    seatingCapacity: 4,
    color: "Napoli Black",
    location: "Chandigarh",
    image: "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=800&q=80",
    images: ["https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=800&q=80"],
    shortDescription: "Legendary off-road 4x4 SUV with mechanical locking differential and removable roof options.",
    description: "The Mahindra Thar is an iconic off-roader designed to conquer mud, sand, and steep inclines. Offers 4WD transfer case with low range, washable interior floor with drain plugs, and touchscreen infotainment.",
    features: ["Shift-on-the-Fly 4WD", "Mechanical Locking Differential", "Roll Cage Protection", "Touchscreen Infotainment", "4-Star NCAP Safety"],
    featured: true,
    condition: "New"
  },
  {
    id: "v17",
    make: "Honda",
    model: "Amaze VX",
    year: 2024,
    category: "Sedan",
    fuelType: "Petrol",
    transmission: "Automatic",
    price: 985000,
    quantity: 5,
    mileage: "18.6 km/l",
    engine: "1199 cc i-VTEC",
    seatingCapacity: 5,
    color: "Radiant Red",
    location: "Lucknow",
    image: "https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?auto=format&fit=crop&w=800&q=80",
    images: ["https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?auto=format&fit=crop&w=800&q=80"],
    shortDescription: "Spacious compact sedan offering smooth CVT automatic transmission and big 420L boot.",
    description: "The Honda Amaze provides sophisticated sedan comfort in a maneuverable footprint. Powered by a refined 1.2L i-VTEC engine paired with smooth CVT transmission, automatic climate control, and paddle shifters.",
    features: ["Smooth CVT Transmission", "Paddle Shifters", "420 Litres Boot Space", "7-inch Digipad Touchscreen", "Rear Camera"],
    featured: false,
    condition: "New"
  },
  {
    id: "v18",
    make: "Honda",
    model: "City 5th Gen ZX",
    year: 2024,
    category: "Sedan",
    fuelType: "Petrol",
    transmission: "Automatic",
    price: 1630000,
    quantity: 3,
    mileage: "18.4 km/l",
    engine: "1498 cc i-VTEC",
    seatingCapacity: 5,
    color: "Golden Brown",
    location: "Ahmedabad",
    image: "https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?auto=format&fit=crop&w=800&q=80",
    images: ["https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?auto=format&fit=crop&w=800&q=80"],
    shortDescription: "Benchmark executive sedan featuring Honda Sensing ADAS safety suite and sunroof.",
    description: "The Honda City is the quintessential mid-size sedan known for silky i-VTEC high-revving performance, plush leatherette upholstery, LaneWatch camera, electric sunroof, and Honda Sensing driver assist.",
    features: ["Honda Sensing ADAS", "LaneWatch Camera", "Full LED Headlamps", "Electric Sunroof", "6 Airbags Standard"],
    featured: true,
    condition: "New"
  },
  {
    id: "v19",
    make: "Honda",
    model: "Elevate ZX",
    year: 2024,
    category: "SUV",
    fuelType: "Petrol",
    transmission: "Automatic",
    price: 1620000,
    quantity: 4,
    mileage: "16.92 km/l",
    engine: "1498 cc i-VTEC",
    seatingCapacity: 5,
    color: "Phoenix Orange",
    location: "Kolkata",
    image: "https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?auto=format&fit=crop&w=800&q=80",
    images: ["https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?auto=format&fit=crop&w=800&q=80"],
    shortDescription: "Urban SUV with bold stance, 220mm ground clearance, and 10.25-inch HD touchscreen.",
    description: "The Honda Elevate combines SUV toughness with legendary Honda reliability and spacious cabin ergonomics. Features 220mm ground clearance, wireless smartphone connectivity, and Honda Sensing ADAS.",
    features: ["220mm Ground Clearance", "10.25-inch HD Display", "Honda Sensing ADAS", "Wireless Charging", "458L Cargo Boot"],
    featured: true,
    condition: "New"
  },
  {
    id: "v20",
    make: "Toyota",
    model: "Glanza V AMT",
    year: 2024,
    category: "Hatchback",
    fuelType: "Petrol",
    transmission: "Automatic",
    price: 998000,
    quantity: 5,
    mileage: "22.9 km/l",
    engine: "1197 cc",
    seatingCapacity: 5,
    color: "Insta Blue",
    location: "Indore",
    image: "https://images.unsplash.com/photo-1590362891991-f776e747a588?auto=format&fit=crop&w=800&q=80",
    images: ["https://images.unsplash.com/photo-1590362891991-f776e747a588?auto=format&fit=crop&w=800&q=80"],
    shortDescription: "Stylish premium hatchback backed by Toyota 3-year / 1,00,000 km warranty peace of mind.",
    description: "The Toyota Glanza offers cool hatchback style paired with Toyota's hassle-free service ecosystem. Equipped with 360-degree camera, HUD, UV-cut glass, cruise control, and 6 airbags safety.",
    features: ["Toyota Warranty Coverage", "360 Surround View Camera", "Head-Up Display", "UV Cut Glass", "6 Airbags"],
    featured: false,
    condition: "New"
  },
  {
    id: "v21",
    make: "Toyota",
    model: "Urban Cruiser Hyryder V Hybrid",
    year: 2024,
    category: "SUV",
    fuelType: "Hybrid",
    transmission: "Automatic",
    price: 1999000,
    quantity: 3,
    mileage: "27.97 km/l",
    engine: "1490 cc Hybrid",
    seatingCapacity: 5,
    color: "Cave Black",
    location: "Ahmedabad",
    image: "https://images.unsplash.com/photo-1580273916550-e323be2ae537?auto=format&fit=crop&w=800&q=80",
    images: ["https://images.unsplash.com/photo-1580273916550-e323be2ae537?auto=format&fit=crop&w=800&q=80"],
    shortDescription: "Self-charging hybrid SUV delivering phenomenal 27.97 km/l mileage and electric silent drive.",
    description: "The Toyota Urban Cruiser Hyryder combines self-charging hybrid EV technology with panoramic sunroof luxury. Enjoy near-silent city cruising in EV mode and confident long-distance highway performance.",
    features: ["Self-Charging Hybrid EV", "Panoramic Sunroof", "Ventilated Leather Seats", "Drive Mode Select", "i-Connect Connected Tech"],
    featured: true,
    condition: "New"
  },
  {
    id: "v22",
    make: "Toyota",
    model: "Innova Hycross ZX (O)",
    year: 2024,
    category: "MUV",
    fuelType: "Hybrid",
    transmission: "Automatic",
    price: 3098000,
    quantity: 2,
    mileage: "23.24 km/l",
    engine: "1987 cc Hybrid",
    seatingCapacity: 7,
    color: "Super White",
    location: "Mumbai",
    image: "https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=800&q=80",
    images: ["https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=800&q=80"],
    shortDescription: "Ultimate luxury MUV with powered Ottoman rear lounge seats and TNGA monocoque chassis.",
    description: "The Toyota Innova Hycross elevates luxury multi-utility travel. Offers powered captain seats with calf legrests, panoramic sunroof, JBL 9-speaker audio, Toyota Safety Sense 3.0, and 5th-gen hybrid power.",
    features: ["Powered Ottoman Captain Seats", "Toyota Safety Sense ADAS", "TNGA Monocoque Chassis", "JBL 9-Speaker Audio", "Powered Tailgate"],
    featured: true,
    condition: "New"
  },
  {
    id: "v23",
    make: "Kia",
    model: "Sonet GTX+ Turbo",
    year: 2024,
    category: "Compact SUV",
    fuelType: "Petrol",
    transmission: "Automatic",
    price: 1475000,
    quantity: 4,
    mileage: "18.3 km/l",
    engine: "998 cc Turbo",
    seatingCapacity: 5,
    color: "Pewter Olive",
    location: "Kochi",
    image: "https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?auto=format&fit=crop&w=800&q=80",
    images: ["https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?auto=format&fit=crop&w=800&q=80"],
    shortDescription: "Aggressive compact SUV loaded with dual 10.25-inch displays, Level 1 ADAS, and Bose audio.",
    description: "The new Kia Sonet brings aggressive tiger-nose styling, ventilated front seats, LED crown jewel headlamps, 360-degree camera, and 10 Level 1 ADAS safety features to the compact SUV segment.",
    features: ["Level 1 ADAS (10 features)", "Dual 10.25 Display Screen", "Bose Premium 7-Speaker Sound", "Ventilated Front Seats", "360 Degree Camera"],
    featured: true,
    condition: "New"
  },
  {
    id: "v24",
    make: "Kia",
    model: "Seltos GTX+ ADAS",
    year: 2024,
    category: "SUV",
    fuelType: "Diesel",
    transmission: "Automatic",
    price: 1999000,
    quantity: 3,
    mileage: "19.1 km/l",
    engine: "1493 cc Diesel",
    seatingCapacity: 5,
    color: "Matte Graphite",
    location: "Ahmedabad",
    image: "https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?auto=format&fit=crop&w=800&q=80",
    images: ["https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?auto=format&fit=crop&w=800&q=80"],
    shortDescription: "Premium mid-SUV with dual panoramic display screen, Level 2 ADAS, and dual-zone climate.",
    description: "The Kia Seltos sets benchmark standards in style and technology. Featuring 17 Level 2 ADAS autonomous features, dual panoramic 10.25-inch screen, panoramic sunroof, electronic parking brake, and Kia Connect.",
    features: ["Level 2 ADAS (17 features)", "Dual Panoramic Screens", "Dual-Zone Climate Control", "Electronic Parking Brake", "Bose 8-Speaker Audio"],
    featured: true,
    condition: "New"
  },
  {
    id: "v25",
    make: "Kia",
    model: "Carens Luxury Plus",
    year: 2024,
    category: "MUV",
    fuelType: "Diesel",
    transmission: "Automatic",
    price: 1895000,
    quantity: 3,
    mileage: "18.5 km/l",
    engine: "1493 cc",
    seatingCapacity: 7,
    color: "Imperial Blue",
    location: "Chennai",
    image: "https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=800&q=80",
    images: ["https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=800&q=80"],
    shortDescription: "Versatile 7-seater recreational family vehicle with one-touch electric tumble 2nd row seats.",
    description: "The Kia Carens offers unmatched 3-row comfort and utility for modern families. Features one-touch electric seat tumble, roof-mounted diffuse AC vents, rear door sunshade curtains, and 6 airbags standard across variants.",
    features: ["One-Touch Electric Seat Tumble", "Roof-Mounted AC Vents", "Rear Door Sunshades", "6 Airbags Standard", "Air Purifier with Virus Protection"],
    featured: false,
    condition: "New"
  },
  {
    id: "v26",
    make: "Skoda",
    model: "Slavia Style 1.5 TSI",
    year: 2024,
    category: "Sedan",
    fuelType: "Petrol",
    transmission: "Automatic",
    price: 1868000,
    quantity: 2,
    mileage: "18.73 km/l",
    engine: "1498 cc TSI",
    seatingCapacity: 5,
    color: "Lava Blue",
    location: "Bengaluru",
    image: "https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?auto=format&fit=crop&w=800&q=80",
    images: ["https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?auto=format&fit=crop&w=800&q=80"],
    shortDescription: "European enthusiast sedan with 150 PS TSI engine and 521-litre class-leading trunk boot.",
    description: "The Skoda Slavia delivers pure European driving dynamics and timeless crystalline design. Powered by 150 PS 1.5 TSI engine with Active Cylinder Technology (ACT), 7-speed DSG transmission, ventilated front seats, and 5-star NCAP safety.",
    features: ["150 PS TSI Engine", "7-Speed DSG Transmission", "5-Star NCAP Rating", "521L Trunk Boot Space", "Active Cylinder Technology"],
    featured: true,
    condition: "New"
  },
  {
    id: "v27",
    make: "Skoda",
    model: "Kushaq Monte Carlo",
    year: 2024,
    category: "SUV",
    fuelType: "Petrol",
    transmission: "Automatic",
    price: 1979000,
    quantity: 3,
    mileage: "17.9 km/l",
    engine: "1498 cc TSI",
    seatingCapacity: 5,
    color: "Tornado Red",
    location: "Mumbai",
    image: "https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?auto=format&fit=crop&w=800&q=80",
    images: ["https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?auto=format&fit=crop&w=800&q=80"],
    shortDescription: "Rally-inspired SUV with blacked-out Monte Carlo badge styling and red interior accents.",
    description: "The Skoda Kushaq Monte Carlo pays tribute to Skoda's motorsport heritage. Features red-tinted virtual cockpit display, dual-tone leather seats, red brake calipers, glass sunroof, and 5-star NCAP crash rating.",
    features: ["Monte Carlo Rally Badge Tech", "Red Virtual Cockpit", "150 PS TSI Engine", "5-Star Global NCAP Rating", "Skoda Sound System"],
    featured: true,
    condition: "New"
  },
  {
    id: "v28",
    make: "Tata",
    model: "Tiago EV Tech Lux",
    year: 2024,
    category: "Electric",
    fuelType: "Electric",
    transmission: "Automatic",
    price: 1189000,
    quantity: 4,
    mileage: "315 km/charge",
    engine: "24 kWh Battery",
    seatingCapacity: 5,
    color: "Teal Blue",
    location: "Ahmedabad",
    image: "https://images.unsplash.com/photo-1560958089-b8a1929cea89?auto=format&fit=crop&w=800&q=80",
    images: ["https://images.unsplash.com/photo-1560958089-b8a1929cea89?auto=format&fit=crop&w=800&q=80"],
    shortDescription: "Accessible urban electric car offering 315 km range and fast DC charging capability.",
    description: "The Tata Tiago EV makes electric car ownership accessible and hassle-free. Features 4-level multi-mode regen, smartwatch connectivity, automatic climate control, fast DC charging, and whisper-quiet cabin driving.",
    features: ["315 km Certified Range", "4-Level Multi-Mode Regen", "DC Fast Charging Capable", "ZConnect Telematics", "Fully Automatic AC"],
    featured: false,
    condition: "New"
  }
];

async function seedVehicles() {
  try {
    console.log('Reading existing vehicles dataset...');
    let existingData = [];
    try {
      const currentContent = await fs.readFile(VEHICLES_FILE, 'utf8');
      existingData = JSON.parse(currentContent);
      
      // Create automatic backup before overwriting
      await fs.writeFile(BACKUP_FILE, JSON.stringify(existingData, null, 2), 'utf8');
      console.log(`Automatic backup saved to ${BACKUP_FILE}`);
    } catch (err) {
      console.log('No existing vehicles file found, starting fresh seeding...');
    }

    // Write the 28 realistic Indian vehicles into vehicles.json
    await fs.writeFile(VEHICLES_FILE, JSON.stringify(DEMO_VEHICLES, null, 2), 'utf8');
    console.log(`Successfully seeded ${DEMO_VEHICLES.length} realistic Indian marketplace vehicles to ${VEHICLES_FILE}`);
  } catch (error) {
    console.error('Error seeding vehicle data:', error);
    process.exit(1);
  }
}

seedVehicles();
